# Change these first
owner: UAL-RE # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: Data Cooperative Site
    url: https://data.library.arizona.edu
    assignees:
      - zoidy
      - jcoliver
  - name: ReDATA
    url: https://arizona.figshare.com
    assignees:
      - yhan818
      - zoidy
      - HafeezOJ
    expectedStatusCodes:      
      - 403
      - 200
      - 201
  - name: ReDATA (stage)
    url: $SECRET_SITE_1
    assignees:
      - yhan818
      - zoidy
      - HafeezOJ
    expectedStatusCodes:
      - 401
      - 403
      - 200
      - 201
  - name: Campus Repository
    url: https://repository.arizona.edu/
    maxResponseTime: 5000
#    assignees:
#      - librariankimberly
#  - name: Spatial Data Explorer
#    url: https://geo.library.arizona.edu/
#    assignees:
#      - kcarini
#  - name: Afghan Respository
#    url: http://www.afghandata.org/
#    assignees:
#      - yhan818
  - name: UAL Janeway
    url: https://journals.librarypublishing.arizona.edu/
    assignees:
      - edubinsky1116
  - name: Arizona Historical Indexes
    url: https://uamr.lib.arizona.edu/
    assignees:
      - librariankimberly 
  - name: UA ORCID
    url: https://orcid.arizona.edu
    assignees:
      - zoidy
      - edubinsky1116

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  baseUrl: /uptime
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://avatars3.githubusercontent.com/u/61063507?s=200&v=4
  name: UAL-RE Web Services Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
